-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTnFrJjeGRndH8lVH
d2J1RTNjuj1iZR5uBGKAjpCd5zKgCgYIKoZIzj0DAQehRANCAATRci7sVsPWt3FY
ubypcnC+p7DkXObtdEymhYaHbaF7AjAtWuqetcd9VPh/k7t+50Uid4G6D0RIN42I
4kigKWVq
-----END PRIVATE KEY-----